### ISSUE TITLE
Add views to generation

### ISSUE THREAD

**Issue by t-andre** [loresoft/EntityFrameworkCore.Generator#12]
Hi,

Thanks for your work.

It's possible to add views when generating entities ?

Thanks

**Comment by pwelter34** [comment]
Soon as EF Core supports views in the generation modal, I'll add support here.  Should be in version 3.0.

**Comment by t-andre** [comment]
> Soon as EF Core supports views in the generation modal, I'll add support here. Should be in version 3.0.

Greate Thanks

**Comment by GunboatDiplomat** [comment]
@pwelter34 any update on this issue? EF Core 3.0 is at Preview 8, which they said is production ready. Are waiting for the RTM?

**Comment by pwelter34** [comment]
views are now supported in version 2.0 of efg
