### ISSUE TITLE
Error running efg on Solus linux: "version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference"

### ISSUE THREAD

**Issue by arcooke** [loresoft/EntityFrameworkCore.Generator#13]
Hi there.

I am using Solus linux, along with Core 3 preview 2 and VS Code.  I am using the dotnet snap package.  It installs fine from the terminal, but throws and error when I try to run `efg`.  Let me know if there is any other info I may need to provide about my environment.

    $ dotnet tool install --global EntityFrameworkCore.Generator --version 1.0.0.36
    You can invoke the tool using the following command: efg
    Tool 'entityframeworkcore.generator' (version '1.0.0.36') was successfully installed.

    $ efg
    efg: relocation error: /usr/lib/libc.so.6: symbol _dl_exception_create, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference

```
$ code-oss --version
1.32.0
48ffb9a4e0d60339a158e57b56a6c1bbf31368a4
x64
```

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010184
 Commit:    c57bde4593

Runtime Environment:
 OS Name:     solus
 OS Version:  3.9999
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /snap/dotnet-sdk/28/sdk/3.0.100-preview-010184/

Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core SDKs installed:
  3.0.100-preview-010184 [/snap/dotnet-sdk/28/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [/snap/dotnet-sdk/28/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [/snap/dotnet-sdk/28/shared/Microsoft.NETCore.App]
```

**Comment by pwelter34** [comment]
sounds like a runtime issue.  Not much we can do about that.
