### ISSUE TITLE
A network-related or instance-specific error occurred while establishing a connection to SQL Server

### ISSUE THREAD

**Issue by figodeng** [loresoft/EntityFrameworkCore.Generator#14]
i was trying to connect to a remote SQL server with connection string as blow.

database:
  connectionString: Data Source=Server1\\A03;Initial Catalog=USA;User Id=USA;Password=USA@2019!;Integrated Security=True

**Comment by pwelter34** [comment]
That is a sql server connection issue, not related to the code base.  Make sure your connection string is correct.
