### ISSUE TITLE
Bug : configuration - entity - relationshipNaming : Preserve don't work

### ISSUE THREAD

**Issue by capslock66** [loresoft/EntityFrameworkCore.Generator#21]
entity:
    relationshipNaming: Preserve

When I set to Suffix, he "List" is well appended
When I set to Plural or don't set relationshipNaming , result is Pluralized (default)
But When I set the relationshipNaming to Preserve, result is  "singularized"
previous relationShip name is not used.

**Comment by pwelter34** [comment]
thanks for opening issue, this is a duplicate of #10

**Comment by capslock66** [comment]
Not really a duplicate of #10 :
   entityNaming: Preserve
   propertyNaming: Preserve
here is on 
   relationshipNaming: Preserve
