### ISSUE TITLE
Breaking changes in EF Core 3.0

### ISSUE THREAD

**Issue by DmytroPotapov** [loresoft/EntityFrameworkCore.Generator#24]
Do you plans to support this new EF core behavior?  

> The return type for several async methods has been changed from Task to ValueTask
https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#the-return-type-for-several-async-methods-has-been-changed-from-task-to-valuetask
https://github.com/aspnet/EntityFrameworkCore/issues/15184

**Comment by bigshiny90** [comment]
Yes, just to add more details on this, here is an example of what is generated currently:

```
public static Task<Entity> GetByKeyAsync(this IQueryable<Entity> queryable, decimal id)
{
  if (queryable is DbSet<Entity> dbSet)
    return dbSet.FindAsync(id);

    return queryable.FirstOrDefaultAsync(q => q.id == id);
}
```

would simply need to become:

```
public static async Task<Entity> GetByKeyAsync(this IQueryable<Entity> queryable, decimal id)
{
  if (queryable is DbSet<Entity> dbSet)
    return await dbSet.FindAsync(id);

    return await queryable.FirstOrDefaultAsync(q => q.id == id);
}
```

Great tool by the way!  Thanks for putting it together.   I'm sure we're all waiting for final net core 3 release before dealing with issues like this ;)

**Comment by pwelter34** [comment]
The generated code in now compatible with EF Core 3.0 in version 2.0 of efg
