### ISSUE TITLE
Use martinjw/dbschemareader to read database schema

### ISSUE THREAD

**Issue by PhenX** [loresoft/EntityFrameworkCore.Generator#26]
I began using [this project](https://github.com/martinjw/dbschemareader/) a little bit to make a POCO + DBContext generator for at least SQL Server, Oracle, and PGSql, and saw your project which seems to be what I wanted to do, but support only SQL Server for now.

martinjw/dbschemareader supports lots of database kinds. I'm not involved in this project at all, but it seems to be a pretty feature complete project.

Furthermore, it has a compare feature which could be useful to regerenate the classes.

**Comment by pwelter34** [comment]
using the EF core database providers works well so far.  May revisit someday, but not likely.
