### ISSUE TITLE
Specify Schema folder in config

### ISSUE THREAD

**Issue by VinayShiva** [loresoft/EntityFrameworkCore.Generator#29]
While composing the yml file we specify which schema's to use. 

> # tables to include or empty to include all
>   # tables:
>   # schemas to include or empty to include all
>   schemas:
>     - Asset
>     - Party
>     - Event
>     - Customer
>     - Order
>     - Venues
>     - Ref

Now i want to specify folder per schema.

>   # entity class file configuration
>   entity:
>     namespace: "{Project.Namespace}.{**Schema**}.Data.Entities" # the entity class namespace
>     directory: '{Project.Directory}\{**Schema**}\Data\Entities' # the entity class output directory

is this possible or the option is to create multiple yml files and stitch the results manually.

**Comment by pwelter34** [comment]
This is a good idea.  I'll work to get support for a `{Schema}` variable added

**Comment by BartBr** [comment]
Hi, I tried using schema as a variable as you suggested.
I found this to be very difficult to get it right.

The naming should only be a unique per namespace.  example: Shema1.Person should not conflict with Schema2.Person, which I think is the whole point of this feature.

Instead of using a variable I set added an option : "AddSchemaToNamespace"

You can check my changes here:
https://github.com/BartBr/EntityFrameworkCore.Generator/commit/7a9cc2fd73ff2cea4a588a083c6cb793d2f3b88d

**Comment by gratik** [comment]
Looking through the changes you suggested that is exactly what I was looking for, we have a number of tables that are identical in name but differ only by schema and keeping them in separate folders and namespaces would allow for us to use this generator, without resorting to separate contexts or using teh prefix schema option, I really hope this is accepted.

**Comment by BartBr** [comment]
I created the PR https://github.com/loresoft/EntityFrameworkCore.Generator/pull/99

**Comment by BartBr** [comment]
@pwelter34 Hi Paul, could you take a look at my pull request #99?
By any means this feature meant to be nonintrusive, if you don't enable this feature, it has no effect on the rest of the program.

Thanks

**Comment by pwelter34** [comment]
thanks for reminder.   i'll take a look this weekend.

**Comment by pwelter34** [comment]
This is implemented in v3

To use the schema in a namespace, directory or class name use the new {Table.Schema} variable in the configuration file.

Documentation: https://efg.loresoft.com/en/latest/variables/\
Sample: https://github.com/loresoft/EntityFrameworkCore.Generator/tree/master/sample/TrackerSchema/TrackerSchema.Core
