### ISSUE TITLE
Self-referencing navigation property renames not retained

### ISSUE THREAD

**Issue by DavidBoone** [loresoft/EntityFrameworkCore.Generator#491]
Love the fact that navigation property renames are now supported!  However, ran into an issue where self-referencing relationships' names were not preserved.

I've attached a sample project with an SQLite database.  `efg generate` was run, and then the two properties were renamed to `ParentThing` and `ChildThings`.  Upon running `efg generate` those names are lost.

[ConsoleApp5.zip](https://github.com/loresoft/EntityFrameworkCore.Generator/files/13210631/ConsoleApp5.zip)

**Comment by pwelter34** [comment]
This issue has a 2 part fix

1.  SQLite doesn't support constraint names, which this feature relies on.  Code updated to generate a name if none found.  You'll have to run the gen command after this update to get the generated constraint names.  Then you are free to rename and it should track the renames
2. Fix issue with Self-referencing navigation property

fix in v6.2.0
