### ISSUE TITLE
How to output files to "Models" folder?

### ISSUE THREAD

**Issue by doggy8088** [loresoft/EntityFrameworkCore.Generator#65]
The output folder `Data\` has been hard-coded. Is it possible output folder as an option?

**Comment by pwelter34** [comment]
I don't think any for the output folders are hard-code.  You can config the output location for all the different types of generated files.  For example, the output for the entities, you set the directory.

https://efg.loresoft.com/en/latest/ef/entity/#configuration

**Comment by doggy8088** [comment]
@pwelter34 I thought the output folder should be assigned in the command argument yesterday. Thanks for let me know. 👍
