### ISSUE TITLE
Feature: append Attributes to entity model properties

### ISSUE THREAD

**Issue by doggy8088** [loresoft/EntityFrameworkCore.Generator#68]
I'd like to append some validation attributes onto properties of a model class. Is it possible to append attributes something like `[JsonIgnore]` or some other attributes to the properties of the model class by any way?

**Comment by dattaproffs** [comment]
Do these attributes really belong in database entity?

**Comment by doggy8088** [comment]
This could be exists in extended properties for SQL Server. Or it can be exists in some other config file. Here is the use case: Anytime I need to re-generate the models, I always need these attributes with these entity's properties.

**Comment by pwelter34** [comment]
Thanks for the suggestion, however the concept of view models is to prevent using the entities directly in an api like that.  If you don't want a column or want to transpose it some way, use a view model.
