### ISSUE TITLE
'efg' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by tong9977** [loresoft/EntityFrameworkCore.Generator#9]
I have installed EntityFrameworkCore.Generator on windows 10.
dotnet tool install --global EntityFrameworkCore.Generator

It has shown install successfully.

but I type efg --help it shown

'efg' is not recognized as an internal or external command, operable program or batch file.

**Comment by pwelter34** [comment]
earlier versions of the .net core sdk had an issue where you had to restart the command prompt for the global command to work.  Try that.

**Comment by tong9977** [comment]
Thank you. It's work.
