### ISSUE TITLE
efg in Windows7?

### ISSUE THREAD

**Issue by win32nipuh** [loresoft/EntityFrameworkCore.Generator#97]
Windows 7
I have installed:
>dotnet tool install --global EntityFrameworkCore.Generator

it successfully installed.
Then: 

> > efg
> 'efg' is not recognized as an internal or external command,
> operable program or batch file.
> 

Is it possible to run efg in Windows 7?

**Comment by pwelter34** [comment]
should work fine.  Have you tried restarting your command prompt?

**Comment by pwelter34** [comment]
Can't reproduces.  Will close in a few days unless I get more information.

**Comment by win32nipuh** [comment]
Yes, it works.
